misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true 
}

exec-once = swaync
exec-once = swww-daemon 
exec-once = /home/baldezh/.local/bin/wallman.sh
exec-once = waybar
exec-once = gammastep -O 5000 

exec-once = pipewire
exec-once = pipewire-pulse
exec-once = sleep 0.5s && wireplumber

exec-once = hyprctl setcursor ArcAurora-cursors 24

env = XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
